apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xccbu97ti-dotnet-basic 
  janus-idp.io/tekton: xccbu97ti-dotnet-basic
  backstage.io/kubernetes-id: xccbu97ti-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xccbu97ti-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  